// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_4M0LLDKsMNn3lAjLPhrZ0TJbNRVdF68',
    appId: '1:80751295809:web:0c098474ced656755175c0',
    messagingSenderId: '80751295809',
    projectId: 'hvnhchat-demo',
    authDomain: 'hvnhchat-demo.firebaseapp.com',
    storageBucket: 'hvnhchat-demo.firebasestorage.app',
    measurementId: 'G-1XB5TN3SFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuNrJ4joxexaO0BEeF9BtvD33ugq2tX4M',
    appId: '1:80751295809:android:0617cb51ec13a9685175c0',
    messagingSenderId: '80751295809',
    projectId: 'hvnhchat-demo',
    storageBucket: 'hvnhchat-demo.firebasestorage.app',
  );
}
